### ISSUE TITLE
No internet connection on Raspberry Pi

### ISSUE THREAD

**Issue by whaleygeek** [AdventuresInMinecraft/AdventuresInMinecraft-Pi#1]
Many teachers don't have Pi's connected to the internet.

Could you pre-build the zip for the Pi starter kit and link it from the github.io page, with instructions to right click and download it, copy it to a memory stick, unzip it on the pi, where to store it.

**Comment by martinohanlon** [comment]
Added some instructions to the website and created a release to download.
